# Generated by Django 2.2.4 on 2019-08-14 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateTimeField(blank=True, null=True)),
                ('date_last_edited', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('height', models.IntegerField(blank=True)),
                ('weight', models.IntegerField(blank=True)),
                ('scr', models.IntegerField(blank=True)),
                ('age_type', models.CharField(choices=[('Y', 'Years'), ('M', 'Months')], default='Y', max_length=1)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('description', models.TextField(help_text='Description for case study scenario.')),
                ('answer_1', models.TextField(help_text='Answer 1')),
                ('answer_2', models.TextField(help_text='Answer 2')),
                ('answer_3', models.TextField(help_text='Answer 3')),
                ('answer_4', models.TextField(help_text='Answer 4')),
                ('feedback', models.TextField(help_text='Case study creator feedback')),
                ('last_edited_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(help_text='Question text body')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Medication Name')),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case_study.CaseStudy')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(help_text='Medical history information')),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case_study.CaseStudy')),
            ],
        ),
        migrations.AddField(
            model_name='casestudy',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case_study.Question'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case_study.Tag'),
        ),
    ]
