# Generated by Django 2.2.4 on 2019-08-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_study', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestudy',
            name='tag',
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='last_edited_user',
            field=models.IntegerField(blank=True),
        ),
    ]
