# Generated by Django 2.2.4 on 2019-09-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_study', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='date_case_created',
            field=models.DateTimeField(blank=True),
        ),
    ]
