# Generated by Django 2.2.4 on 2019-09-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_anon',
            field=models.BooleanField(null=True),
        ),
    ]
