# Generated by Django 2.2.4 on 2019-08-15 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('case_study', '0002_auto_20190814_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='scr',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='weight',
            field=models.FloatField(blank=True),
        ),
    ]
