# Generated by Django 2.2.4 on 2019-08-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_study', '0002_auto_20190820_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='answer',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True),
        ),
    ]
