# Generated by Django 2.2.4 on 2019-09-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_study', '0002_auto_20190904_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='date_case_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
