# Generated by Django 2.2.4 on 2019-10-11 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('case_study', '0002_other'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_body', models.TextField()),
                ('comment_date', models.DateTimeField()),
                ('report_date', models.DateTimeField()),
                ('reason', models.TextField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_comment', to='case_study.Comment')),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_comment_author', to=settings.AUTH_USER_MODEL)),
                ('report_author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
