# Generated by Django 2.2.4 on 2019-09-05 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_study', '0003_auto_20190904_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestudy',
            name='date_case_created',
        ),
        migrations.AddField(
            model_name='casestudy',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
