# Generated by Django 2.2.4 on 2019-08-20 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case_study', '0003_auto_20190815_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagRelationships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case_study.CaseStudy')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case_study.Tag')),
            ],
        ),
    ]
