# Generated by Django 2.2.4 on 2019-10-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_study', '0003_commentreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreport',
            name='report_author_email',
            field=models.EmailField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentreport',
            name='report_author_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
