# Generated by Django 2.2.4 on 2019-08-20 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_study', '0003_casestudy_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casestudy',
            old_name='answer_1',
            new_name='answer_a',
        ),
        migrations.RenameField(
            model_name='casestudy',
            old_name='answer_2',
            new_name='answer_b',
        ),
        migrations.RenameField(
            model_name='casestudy',
            old_name='answer_3',
            new_name='answer_c',
        ),
        migrations.RenameField(
            model_name='casestudy',
            old_name='answer_4',
            new_name='answer_d',
        ),
    ]
