# Generated by Django 2.2.4 on 2019-08-15 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_study', '0003_auto_20190815_0057'),
        ('case_study', '0003_auto_20190814_2158'),
    ]

    operations = [
    ]
