# Generated by Django 2.2.4 on 2019-10-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_study', '0004_auto_20191015_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_appropriate',
            field=models.BooleanField(default=True),
        ),
    ]
