# Generated by Django 2.2.4 on 2019-08-18 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case_study', '0004_merge_20190815_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='answer_1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='answer_2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='answer_3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='answer_4',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='date_last_edited',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='date_submitted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='feedback',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='last_edited_user',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='scr',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='TagRelationships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case_study.CaseStudy')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case_study.Tag')),
            ],
        ),
    ]
