# Generated by Django 2.2.4 on 2019-10-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_study', '0004_commentreport_report_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_deleted',
            field=models.BooleanField(null=True),
        ),
    ]
