# Generated by Django 2.2.4 on 2019-08-18 10:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('case_study', '0005_auto_20190818_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 18, 10, 24, 44, 858207, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='date_last_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='date_submitted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='height',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='last_edited_user',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='scr',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='weight',
            field=models.FloatField(blank=True),
        ),
    ]
