# Generated by Django 2.2.4 on 2019-10-17 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_study', '0005_comment_comment_appropriate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_appropriate',
            new_name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='commentreport',
            name='report_author_email',
        ),
        migrations.RemoveField(
            model_name='commentreport',
            name='report_author_name',
        ),
    ]
