# Generated by Django 2.2.4 on 2019-08-18 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_study', '0006_auto_20190818_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
