# Generated by Django 2.2.4 on 2019-10-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_study', '0006_auto_20191011_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
