# Generated by Django 2.2.4 on 2019-08-18 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case_study', '0007_auto_20190818_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='answer_1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='answer_2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='answer_3',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='answer_4',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='date_last_edited',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='date_submitted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='feedback',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='last_edited_user',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='case_study.Question'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='scr',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='body',
            field=models.TextField(),
        ),
    ]
