# Generated by Django 2.2.4 on 2019-10-16 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case_study', '0007_casestudy_is_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestudy',
            name='date_last_edited',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='is_draft',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='is_submitted',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='last_edited_user',
        ),
        migrations.AddField(
            model_name='casestudy',
            name='case_state',
            field=models.CharField(choices=[('D', 'D'), ('R', 'R'), ('P', 'P')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='age_type',
            field=models.CharField(blank=True, choices=[('Y', 'Years'), ('M', 'Months')], default='Y', max_length=1),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='date_submitted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case_study.Question'),
        ),
    ]
