# Generated by Django 2.2.4 on 2019-08-19 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case_study', '0008_auto_20190818_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='case_study.Question'),
        ),
    ]
