# Generated by Django 2.2.4 on 2019-08-19 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case_study', '0008_auto_20190818_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='age_type',
            field=models.CharField(blank=True, choices=[('Y', 'Years'), ('M', 'Months')], default='Y', max_length=1),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='answer_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='answer_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='answer_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='answer_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='date_last_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='date_submitted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='last_edited_user',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='case_study.Question'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='scr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
