# Generated by Django 2.2.4 on 2019-08-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_study', '0009_auto_20190819_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
