# Generated by Django 2.2.4 on 2019-08-20 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_study', '0010_auto_20190820_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
