# Generated by Django 2.2.4 on 2019-08-16 07:55

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('django_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name_first', models.CharField(default='', max_length=20)),
                ('name_last', models.CharField(default='', max_length=20)),
                ('avatar', models.ImageField(default='/static/img/profile-default.png', upload_to=accounts.models.PathAndRename('avatars/'))),
                ('bio', models.CharField(blank=True, default='', max_length=160)),
                ('gender', models.CharField(default='Male', max_length=20)),
                ('dob', models.DateField(blank=True)),
                ('study_commenced', models.DateField()),
            ],
        ),
    ]
