<<<<<<< HEAD
# Generated by Django 2.2.4 on 2019-08-17 08:58

import accounts.models
from django.db import migrations, models
=======
# Generated by Django 2.2.4 on 2019-08-16 07:55

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
>>>>>>> 73da5868f99877ff35d4427b3dd90a3c5b2af9b4


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=40)),
                ('last_name', models.CharField(blank=True, max_length=60)),
                ('university', models.CharField(blank=True, max_length=150)),
                ('degree_commencement_year', models.IntegerField(blank=True, help_text='Year of pharmacy degree commencement', null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', accounts.models.UserManager()),
=======
            name='UserProfile',
            fields=[
                ('django_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name_first', models.CharField(default='', max_length=20)),
                ('name_last', models.CharField(default='', max_length=20)),
                ('avatar', models.ImageField(default='/static/img/profile-default.png', upload_to=accounts.models.PathAndRename('avatars/'))),
                ('bio', models.CharField(blank=True, default='', max_length=160)),
                ('gender', models.CharField(default='Male', max_length=20)),
                ('dob', models.DateField(blank=True)),
                ('study_commenced', models.DateField()),
>>>>>>> 73da5868f99877ff35d4427b3dd90a3c5b2af9b4
            ],
        ),
    ]
