# Generated by Django 2.2.4 on 2019-09-12 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reset_attempts_date',
        ),
    ]
