# Generated by Django 2.2.4 on 2019-10-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_report_silenced',
            field=models.BooleanField(default=False),
        ),
    ]
